# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('coupon_code', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('coupons_used', models.ManyToManyField(blank=True, to='wallet.Coupon')),
                ('orders', models.ManyToManyField(blank=True, to='commodity.Order')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('is_refunded', models.BooleanField(default=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Order')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.EWallet')),
            ],
        ),
    ]
