# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0001_initial'),
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('D', 'Delivering'), ('A', 'Absent'), ('I', 'Idle')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('authen.user',),
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_type', models.CharField(choices=[('H', 'Home-Delivery'), ('I', 'In-Hand Delivery')], max_length=1)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.DeliveryPerson')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commodity.Order')),
            ],
        ),
    ]
